version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:7.17.2
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - es_net
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.17.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es_net
networks:
  es_net:
    driver: bridge
